server:
   port: 9000
---
enviroment: prov
spring:
   config:
     activate:
       on-profile: prod
server:
  port: 5000
myCustomEnvs:
  welcomeMsg: Hello from Prod
---
enviroment: test
spring:
   config:
    activate:
     on-profile: test
server:
  port: 4000
myCustomEnvs:
   welcomeMsg: Hello from Test